-- MySQL Script generated by MySQL Workbench
-- 03/27/19 16:42:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apps_revista_documental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apps_revista_documental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apps_revista_documental` DEFAULT CHARACTER SET utf8 ;
USE `apps_revista_documental` ;

-- -----------------------------------------------------
-- Table `apps_revista_documental`.`cat_tipodocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`cat_tipodocumento` (
  `id_cat_tipodocumento` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cat_tipodocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`cat_terminacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`cat_terminacion` (
  `id_cat_terminacion` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(20) NOT NULL,
  `terminacion_a` VARCHAR(1) NOT NULL,
  `terminacion_b` VARCHAR(1) NOT NULL,
  `mes` INT NOT NULL,
  `anio` INT NOT NULL,
  PRIMARY KEY (`id_cat_terminacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`cat_tipolicencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`cat_tipolicencia` (
  `id_cat_tipolicencia` INT NOT NULL AUTO_INCREMENT,
  `tipo_licencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cat_tipolicencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`licencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`licencia` (
  `id_licencia` INT NOT NULL AUTO_INCREMENT,
  `folio` VARCHAR(45) NOT NULL,
  `vigencia` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `paterno` VARCHAR(45) NOT NULL,
  `materno` VARCHAR(45) NOT NULL,
  `curp_rfc` VARCHAR(45) NOT NULL,
  `cat_tipolicencia_id` INT NOT NULL,
  PRIMARY KEY (`id_licencia`),
  INDEX `fk_licencia_cat_tipolicencia1_idx` (`cat_tipolicencia_id` ASC),
  CONSTRAINT `fk_licencia_cat_tipolicencia1`
    FOREIGN KEY (`cat_tipolicencia_id`)
    REFERENCES `apps_revista_documental`.`cat_tipolicencia` (`id_cat_tipolicencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`cat_codigopostal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`cat_codigopostal` (
  `id_cat_codigopostal` INT NOT NULL AUTO_INCREMENT,
  `codigo_postal` VARCHAR(6) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `municipio` VARCHAR(255) NOT NULL,
  `colonia` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cat_codigopostal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`vehiculo` (
  `id_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NOT NULL,
  `cvt_vehiculo` VARCHAR(45) NOT NULL,
  `tarjeta_circulacion` VARCHAR(45) NOT NULL,
  `nombre_propietario` VARCHAR(45) NOT NULL,
  `paterno_propietario` VARCHAR(45) NOT NULL,
  `materno_propietario` VARCHAR(45) NOT NULL,
  `curp_rfc` VARCHAR(45) NOT NULL,
  `serie_vehicular` VARCHAR(45) NOT NULL,
  `clave_vehicular` VARCHAR(45) NOT NULL,
  `motor` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `linea` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `combustible` VARCHAR(45) NOT NULL,
  `email_propietario` VARCHAR(45) NULL,
  `telefono_propietario` VARCHAR(45) NULL,
  `calle` VARCHAR(100) NOT NULL,
  `noexterior` VARCHAR(45) NOT NULL,
  `cat_codigopostal_id` INT NOT NULL,
  `licencia_id` INT NOT NULL,
  `cat_terminacion_id` INT NOT NULL,
  `fecha_registro` TIMESTAMP NOT NULL,
  UNIQUE INDEX `serie_UNIQUE` (`serie_vehicular` ASC),
  INDEX `fk_generales_cat_terminacion1_idx` (`id_vehiculo` ASC),
  INDEX `fk_generales_licencia1_idx` (`licencia_id` ASC),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC),
  PRIMARY KEY (`id_vehiculo`),
  INDEX `fk_generales_cat_terminacion1` (`cat_terminacion_id` ASC),
  INDEX `fk_vehiculo_cat_codigopostal1_idx` (`cat_codigopostal_id` ASC),
  CONSTRAINT `fk_generales_cat_terminacion1`
    FOREIGN KEY (`cat_terminacion_id`)
    REFERENCES `apps_revista_documental`.`cat_terminacion` (`id_cat_terminacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_generales_licencia1`
    FOREIGN KEY (`licencia_id`)
    REFERENCES `apps_revista_documental`.`licencia` (`id_licencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_cat_codigopostal1`
    FOREIGN KEY (`cat_codigopostal_id`)
    REFERENCES `apps_revista_documental`.`cat_codigopostal` (`id_cat_codigopostal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`cat_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`cat_modulo` (
  `id_cat_modulo` INT NOT NULL AUTO_INCREMENT,
  `modulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cat_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `paterno` VARCHAR(45) NULL,
  `materno` VARCHAR(45) NULL DEFAULT NULL,
  `curp` VARCHAR(45) NULL,
  `cat_modulo_id` INT NOT NULL,
  `remember_token` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_cat_modulo1_idx` (`cat_modulo_id` ASC),
  UNIQUE INDEX `curp_UNIQUE` (`curp` ASC),
  CONSTRAINT `fk_user_cat_modulo1`
    FOREIGN KEY (`cat_modulo_id`)
    REFERENCES `apps_revista_documental`.`cat_modulo` (`id_cat_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `rfc` VARCHAR(45) NOT NULL,
  `razon_social` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id_empresa`),
  INDEX `fk_empresa_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_empresa_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `apps_revista_documental`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`vehiculo_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`vehiculo_empresa` (
  `id_vehiculo_empresa` INT NOT NULL AUTO_INCREMENT,
  `vehiculo_id` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  `fecha_ingreso` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_vehiculo_empresa`),
  INDEX `fk_vehiculo_empresa_vehiculo1_idx` (`vehiculo_id` ASC),
  INDEX `fk_vehiculo_empresa_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_vehiculo_empresa_vehiculo1`
    FOREIGN KEY (`vehiculo_id`)
    REFERENCES `apps_revista_documental`.`vehiculo` (`id_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_empresa_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `apps_revista_documental`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`carga_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`carga_documento` (
  `id_carga_documento` INT NOT NULL AUTO_INCREMENT,
  `vehiculo_empresa_id` INT NOT NULL,
  `cat_tipodocumento_id` INT NOT NULL,
  `fecha_carga` TIMESTAMP NOT NULL,
  `estatus_carga` ENUM('PENDIENTE', 'CORRECTO', 'RECHAZADO', 'APELACION') NOT NULL,
  `ip_carga` VARCHAR(45) NULL,
  `user_revision` INT NULL DEFAULT NULL,
  `descripcion_revision` VARCHAR(255) NULL,
  PRIMARY KEY (`id_carga_documento`),
  INDEX `fk_carga_documento_cat_tipo_documento_idx` (`cat_tipodocumento_id` ASC),
  INDEX `fk_carga_documento_user1_idx` (`user_revision` ASC),
  INDEX `fk_carga_documento_vehiculo_empresa1_idx` (`vehiculo_empresa_id` ASC),
  CONSTRAINT `fk_carga_documento_cat_tipo_documento`
    FOREIGN KEY (`cat_tipodocumento_id`)
    REFERENCES `apps_revista_documental`.`cat_tipodocumento` (`id_cat_tipodocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carga_documento_user1`
    FOREIGN KEY (`user_revision`)
    REFERENCES `apps_revista_documental`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carga_documento_vehiculo_empresa1`
    FOREIGN KEY (`vehiculo_empresa_id`)
    REFERENCES `apps_revista_documental`.`vehiculo_empresa` (`id_vehiculo_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`cat_tipopago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`cat_tipopago` (
  `id_cat_tipopago` INT NOT NULL AUTO_INCREMENT,
  `concepto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cat_tipopago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `display_name` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`role_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`role_user` (
  `role_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `fk_table2_roles1_idx` (`role_id` ASC),
  INDEX `fk_table2_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_table2_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `apps_revista_documental`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `apps_revista_documental`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`folio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`folio` (
  `id_folio` INT NOT NULL AUTO_INCREMENT,
  `folio` VARCHAR(45) NOT NULL,
  `periodo` INT NOT NULL,
  `fecha_ingreso` TIMESTAMP NOT NULL,
  `estatusfolio` ENUM('DISPONIBLE', 'OCUPADO', 'CANCELADO') NOT NULL,
  `cat_modulo_id` INT NOT NULL,
  `users_ingreso` INT NOT NULL,
  `users_utilizacion` INT NOT NULL,
  `fecha_utilizacion` VARCHAR(45) NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_folio`),
  INDEX `fk_folios_cat_modulo1_idx` (`cat_modulo_id` ASC),
  INDEX `fk_folios_users1_idx` (`users_ingreso` ASC),
  INDEX `fk_folios_users2_idx` (`users_utilizacion` ASC),
  CONSTRAINT `fk_folios_cat_modulo1`
    FOREIGN KEY (`cat_modulo_id`)
    REFERENCES `apps_revista_documental`.`cat_modulo` (`id_cat_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_folios_users1`
    FOREIGN KEY (`users_ingreso`)
    REFERENCES `apps_revista_documental`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_folios_users2`
    FOREIGN KEY (`users_utilizacion`)
    REFERENCES `apps_revista_documental`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`revista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`revista` (
  `id_revista` INT NOT NULL AUTO_INCREMENT,
  `vehiculo_empresa_id` INT NOT NULL,
  `documental` ENUM('AGREGADO', 'PENDIENTE', 'APROBADO', 'RECHAZADO', 'APELACION') NOT NULL,
  `fecha_documental` TIMESTAMP NOT NULL,
  `fisica` ENUM('AGREGADO', 'PENDIENTE', 'APROBADO', 'RECHAZADO') NOT NULL,
  `fecha_fisica` TIMESTAMP NULL,
  `folio_id` INT NULL,
  `intento` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_revista`),
  INDEX `fk_revista_folios1_idx` (`folio_id` ASC),
  INDEX `fk_revista_vehiculo_empresa1_idx` (`vehiculo_empresa_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`folio_id`)
    REFERENCES `apps_revista_documental`.`folio` (`id_folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_revista_vehiculo_empresa1`
    FOREIGN KEY (`vehiculo_empresa_id`)
    REFERENCES `apps_revista_documental`.`vehiculo_empresa` (`id_vehiculo_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`verificacion_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`verificacion_email` (
  `id_verificacion_email` INT NOT NULL AUTO_INCREMENT,
  `ip_registro` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `ip_confirmacion` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id_verificacion_email`),
  INDEX `IDX_email` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`seguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`seguro` (
  `id_seguro` INT NOT NULL AUTO_INCREMENT,
  `aseguradora` VARCHAR(45) NOT NULL,
  `folio_poliza` VARCHAR(45) NOT NULL,
  `vencimiento_poliza` VARCHAR(45) NOT NULL,
  `cobertura` VARCHAR(45) NOT NULL,
  `vehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id_seguro`),
  INDEX `fk_seguro_generales1_idx` (`vehiculo_id` ASC),
  CONSTRAINT `fk_seguro_generales1`
    FOREIGN KEY (`vehiculo_id`)
    REFERENCES `apps_revista_documental`.`vehiculo` (`id_vehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apps_revista_documental`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apps_revista_documental`.`pago` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `linea_captura` VARCHAR(45) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `fecha_pago` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `cat_tipopago_id` INT NOT NULL,
  `vehiculo_empresa_id` INT NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_pago_cat_tipopago1_idx` (`cat_tipopago_id` ASC),
  INDEX `fk_pago_vehiculo_empresa1_idx` (`vehiculo_empresa_id` ASC),
  CONSTRAINT `fk_pago_cat_tipopago1`
    FOREIGN KEY (`cat_tipopago_id`)
    REFERENCES `apps_revista_documental`.`cat_tipopago` (`id_cat_tipopago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_vehiculo_empresa1`
    FOREIGN KEY (`vehiculo_empresa_id`)
    REFERENCES `apps_revista_documental`.`vehiculo_empresa` (`id_vehiculo_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
